#!/bin/bash
# Klassik DB - Quick SQL Commands Cheat Sheet

# Farben
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Klassik DB - PostgreSQL Cheat Sheet${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${BLUE}▶ In psql einloggen:${NC}"
echo "  sudo -u postgres psql -d klassik"
echo ""

echo -e "${BLUE}▶ Häufigste SQL-Befehle:${NC}"
echo ""

echo -e "${YELLOW}📋 USERS TABELLE${NC}"
echo ""
echo "  # Alle Users anzeigen"
echo "  SELECT * FROM users;"
echo ""
echo "  # Nur wichtige Felder"
echo "  SELECT id, email, address, created_at FROM users ORDER BY created_at DESC;"
echo ""
echo "  # User nach Email suchen"
echo "  SELECT * FROM users WHERE email = 'test@example.com';"
echo ""
echo "  # User nach Wallet-Adresse suchen"
echo "  SELECT * FROM users WHERE address = '0x1234...';"
echo ""
echo "  # Nur Wallet-Users (ohne Email)"
echo "  SELECT id, address, created_at FROM users WHERE email IS NULL;"
echo ""
echo "  # Users mit aktivem Nonce"
echo "  SELECT id, email, address, nonce, nonce_expiry FROM users WHERE nonce IS NOT NULL;"
echo ""
echo "  # Anzahl Users"
echo "  SELECT COUNT(*) FROM users;"
echo ""
echo "  # Letzten 5 Registrierungen"
echo "  SELECT id, email, address, created_at FROM users ORDER BY created_at DESC LIMIT 5;"
echo ""

echo -e "${YELLOW}✏️  DATEN ÄNDERN${NC}"
echo ""
echo "  # Email aktualisieren"
echo "  UPDATE users SET email = 'new@example.com' WHERE id = 1;"
echo ""
echo "  # Wallet-Adresse hinzufügen"
echo "  UPDATE users SET address = '0xabc...' WHERE email = 'user@example.com';"
echo ""
echo "  # Nonce löschen (nach Login)"
echo "  UPDATE users SET nonce = NULL, nonce_expiry = NULL WHERE id = 1;"
echo ""
echo "  # Abgelaufene Nonces löschen (Cleanup)"
echo "  UPDATE users SET nonce = NULL, nonce_expiry = NULL WHERE nonce_expiry < CURRENT_TIMESTAMP;"
echo ""
echo "  # User löschen"
echo "  DELETE FROM users WHERE id = 1;"
echo ""

echo -e "${YELLOW}📊 STATISTIKEN${NC}"
echo ""
echo "  # Anzahl Email-Users vs Wallet-Users"
echo "  SELECT "
echo "    COUNT(*) FILTER (WHERE email IS NOT NULL) as email_users,"
echo "    COUNT(*) FILTER (WHERE address IS NOT NULL) as wallet_users,"
echo "    COUNT(*) as total_users"
echo "  FROM users;"
echo ""
echo "  # Registrierungen pro Tag (letzte 7 Tage)"
echo "  SELECT DATE(created_at) as date, COUNT(*) as registrations"
echo "  FROM users"
echo "  WHERE created_at > CURRENT_DATE - INTERVAL '7 days'"
echo "  GROUP BY DATE(created_at)"
echo "  ORDER BY date DESC;"
echo ""

echo -e "${YELLOW}🔗 JOINS (mit anderen Tabellen)${NC}"
echo ""
echo "  # Orders mit User-Info"
echo "  SELECT o.id, u.email, u.address, o.from_chain, o.to_chain, o.status, o.created_at"
echo "  FROM orders o"
echo "  JOIN users u ON o.user_id = u.id"
echo "  ORDER BY o.created_at DESC;"
echo ""
echo "  # Bookings mit User und Event"
echo "  SELECT b.id, u.email, e.title, b.quantity, b.created_at"
echo "  FROM bookings b"
echo "  JOIN users u ON b.user_id = u.id"
echo "  JOIN events e ON b.event_id = e.id;"
echo ""

echo -e "${YELLOW}🛠️  VERWALTUNG${NC}"
echo ""
echo "  # Alle Tabellen anzeigen"
echo "  \dt"
echo ""
echo "  # Tabellen-Struktur"
echo "  \d users"
echo ""
echo "  # Datenbank-Größe"
echo "  SELECT pg_size_pretty(pg_database_size('klassik'));"
echo ""
echo "  # Verbindungen anzeigen"
echo "  SELECT count(*) FROM pg_stat_activity WHERE datname = 'klassik';"
echo ""
echo "  # Backup erstellen"
echo "  \! pg_dump klassik > backup_\$(date +%Y%m%d).sql"
echo ""
echo "  # psql verlassen"
echo "  \q"
echo ""

echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}💡 Tipps:${NC}"
echo ""
echo "  • Alle SQL-Befehle mit ; abschließen"
echo "  • CTRL+C zum Abbrechen einer Query"
echo "  • \? für alle psql-Befehle"
echo "  • \h SELECT für SQL-Hilfe"
echo ""
echo -e "${BLUE}📖 Vollständige Anleitung:${NC}"
echo "  cat UBUNTU_SETUP.md"
echo ""
